import Head from "next/head";
import React from "react";


const about = (props: any) => {
  return (
    <div>
      <Head>
        <title>Boarding Kennels</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>About</h1>
      <li>{props.users}</li>
    </div>
  );
};

export default about;


