import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useSession, signIn, signOut, getSession } from "next-auth/react";
import HeroSection from "../components/LandingPageComponents/HeroSection/HeroSection";
import Services from "../components/LandingPageComponents/Services/Services";
import Testimonials from "../components/LandingPageComponents/Testimonials/Testimonials";
export async function getServerSideProps(context) {
  return {
    props: {
      session: await getSession(context),
    },
  };
}


import styles from "../styles/Home.module.css";

export default function Home() {
  // const {data, isLoading} = trpc.useQuery(["users.getUser"])
  
    return (
      <div>
        <Head>
          <title>Boarding Kennels</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

      <main className="">
        <HeroSection />
        <Services />
        <Testimonials />
        {/* <h1>Accomodation for all your pets</h1> */}
      </main>
    </div>
  );

}

