import Head from "next/head";
import { trpc } from "../utils/trpc";
import HeroSection from "../components/HeroSection/HeroSection";
import Services from "../components/Services/Services";
import Testimonials from "../components/Testimonials/Testimonials";

// import styles from "../styles/Home.module.css";

export default function Home() {
  const {data, isLoading} = trpc.useQuery(["users.getUser"])

  if (isLoading || !data) return <div>Loading...</div>

  return (
    <div>
      <Head>
        <title>Boarding Kennels</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <HeroSection />
        <Services />
        <Testimonials />
        {/* <h1>Accomodation for all your pets</h1> */}
      </main>
    </div>
  );
}
