import Head from "next/head";
import HeroSection from "../components/HeroSection/HeroSection";
import Services from "../components/Services/Services";
// import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Boarding Kennels</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <HeroSection />
        <Services />
        {/* <h1>Accomodation for all your pets</h1> */}
      </main>
    </div>
  );
}
